name: DORA Metrics
on:
  # Schedule to run weekly
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight every Sunday
  # Allow manual triggering
  workflow_dispatch:
  
jobs:
  collect-metrics:
    runs-on: ubuntu-latest
    steps:
      # No external actions - just direct shell commands
      - name: Calculate DORA Metrics
        run: |
          # Create directory for badge files
          mkdir -p .github/badges
          
          # Clone the repository to access its history
          git clone https://github.com/${{ github.repository }}.git repo
          cd repo
          
          # Get date 30 days ago in ISO format
          THIRTY_DAYS_AGO=$(date -d "30 days ago" -u +"%Y-%m-%dT%H:%M:%SZ")
          
          # Calculate deployment frequency (using git commits as a proxy)
          echo "Calculating Deployment Frequency..."
          DEPLOY_COUNT=$(git log --since="30 days ago" --pretty=format:"%h" | wc -l)
          
          if [ "$DEPLOY_COUNT" -gt 0 ]; then
            DEPLOY_PER_DAY=$(echo "scale=2; $DEPLOY_COUNT / 30" | bc)
            
            if (( $(echo "$DEPLOY_PER_DAY >= 1" | bc -l) )); then
              DF_MESSAGE="$DEPLOY_PER_DAY per day (Elite)"
              DF_COLOR="brightgreen"
            elif (( $(echo "$DEPLOY_PER_DAY >= 0.14" | bc -l) )); then
              DEPLOY_PER_WEEK=$(echo "scale=2; $DEPLOY_PER_DAY * 7" | bc)
              DF_MESSAGE="$DEPLOY_PER_WEEK per week (High)"
              DF_COLOR="green"
            else
              DEPLOY_PER_MONTH=$(echo "scale=2; $DEPLOY_PER_DAY * 30" | bc)
              DF_MESSAGE="$DEPLOY_PER_MONTH per month (Medium)"
              DF_COLOR="yellow"
            fi
          else
            DF_MESSAGE="No deployments (Low)"
            DF_COLOR="red"
          fi
          
          # Create deployment frequency badge file
          cat > ../.github/badges/deployment-frequency.json << EOF
          {
            "schemaVersion": 1,
            "label": "Deployment Frequency",
            "message": "$DF_MESSAGE",
            "color": "$DF_COLOR"
          }
          EOF
          
          # Create a combined DORA metrics badge file
          cat > ../.github/badges/dora-metrics.json << EOF
          {
            "schemaVersion": 1,
            "label": "DORA Metrics",
            "message": "Basic Tracking",
            "color": "blue"
          }
          EOF
          
          echo "DORA metrics calculation complete"
          
          # Go back to the original directory
          cd ..
          
          # Display instructions for README badges
          echo "Add these badges to your README.md:"
          echo "![Deployment Frequency](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/${{ github.repository }}/main/.github/badges/deployment-frequency.json)"
          echo "![DORA Metrics](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/${{ github.repository }}/main/.github/badges/dora-metrics.json)"
      
      # Store badge files as artifacts
      - name: Store badge files
        uses: actions/upload-artifact@v2
        with:
          name: badge-files
          path: .github/badges/