name: Collect DORA Metrics
on:
  # Run weekly to track metrics over time
  schedule:
    - cron: '0 0 * * 0'  # Run at midnight every Sunday
  # Allow manual trigger
  workflow_dispatch:
  
jobs:
  collect-dora-metrics:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write  # Required to update badge files
      pull-requests: read
      issues: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for accurate git history analysis
      
      # Create directory for badge data
      - name: Create badge directory
        run: mkdir -p .github/badges
      
      #############################################################
      # 1. Deployment Frequency
      #############################################################
      
      # Calculate deployment frequency directly with GitHub API
      - name: Calculate Deployment Frequency
        id: deployment-frequency
        run: |
          # Get date 30 days ago in ISO format
          THIRTY_DAYS_AGO=$(date -d "30 days ago" -u +"%Y-%m-%dT%H:%M:%SZ")
          
          # Get workflow runs for the deploy workflow
          DEPLOY_WORKFLOW_RUNS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy-to-production.yml/runs?status=completed&created=>$THIRTY_DAYS_AGO&per_page=100")
          
          # Count successful workflow runs
          DEPLOY_COUNT=$(echo "$DEPLOY_WORKFLOW_RUNS" | jq '[.workflow_runs[] | select(.conclusion == "success")] | length')
          
          if [ -z "$DEPLOY_COUNT" ] || [ "$DEPLOY_COUNT" == "null" ]; then
            DEPLOY_COUNT=0
          fi
          
          # Calculate deployments per day
          DEPLOY_PER_DAY=$(echo "scale=2; $DEPLOY_COUNT / 30" | bc)
          
          # Format the value
          if (( $(echo "$DEPLOY_PER_DAY >= 1" | bc -l) )); then
            DF_VALUE="$DEPLOY_PER_DAY per day"
            DF_LEVEL="Elite"
            DF_COLOR="brightgreen"
          elif (( $(echo "$DEPLOY_PER_DAY >= 0.14" | bc -l) )); then
            DEPLOY_PER_WEEK=$(echo "scale=2; $DEPLOY_PER_DAY * 7" | bc)
            DF_VALUE="$DEPLOY_PER_WEEK per week"
            DF_LEVEL="High"
            DF_COLOR="green"
          elif (( $(echo "$DEPLOY_PER_DAY >= 0.03" | bc -l) )); then
            DEPLOY_PER_MONTH=$(echo "scale=2; $DEPLOY_PER_DAY * 30" | bc)
            DF_VALUE="$DEPLOY_PER_MONTH per month"
            DF_LEVEL="Medium"
            DF_COLOR="yellow"
          else
            DEPLOY_PER_MONTH=$(echo "scale=2; $DEPLOY_PER_DAY * 30" | bc)
            if [ "$DEPLOY_PER_MONTH" = "0" ] || [ "$DEPLOY_PER_MONTH" = "0.00" ]; then
              DF_VALUE="0 per month"
            else
              DF_VALUE="$DEPLOY_PER_MONTH per month"
            fi
            DF_LEVEL="Low"
            DF_COLOR="red"
          fi
          
          echo "deploy_count=$DEPLOY_COUNT" >> $GITHUB_OUTPUT
          echo "df_value=$DF_VALUE" >> $GITHUB_OUTPUT
          echo "df_level=$DF_LEVEL" >> $GITHUB_OUTPUT
          echo "df_color=$DF_COLOR" >> $GITHUB_OUTPUT
      
      # Create deployment frequency badge data
      - name: Generate Deployment Frequency Badge
        run: |
          cat > .github/badges/deployment-frequency.json << EOF
          {
            "schemaVersion": 1,
            "label": "Deployment Frequency",
            "message": "${{ steps.deployment-frequency.outputs.df_value }} (${{ steps.deployment-frequency.outputs.df_level }})",
            "color": "${{ steps.deployment-frequency.outputs.df_color }}"
          }
          EOF
      
      #############################################################
      # 2. Lead Time for Changes
      #############################################################
      
      # Calculate lead time for changes 
      - name: Calculate Lead Time for Changes
        id: lead-time
        run: |
          # Get date 30 days ago in ISO format
          THIRTY_DAYS_AGO=$(date -d "30 days ago" -u +"%Y-%m-%dT%H:%M:%SZ")
          
          # Get merged PRs in the last 30 days
          MERGED_PRS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&sort=updated&direction=desc&per_page=100" | \
            jq '[.[] | select(.merged_at != null) | select(.merged_at > "'"$THIRTY_DAYS_AGO"'")]')
          
          PR_COUNT=$(echo "$MERGED_PRS" | jq 'length')
          
          if [ "$PR_COUNT" -gt 0 ]; then
            # Calculate total time for all PRs (created to merged)
            TOTAL_HOURS=0
            
            for i in $(seq 0 $(($PR_COUNT-1))); do
              CREATED=$(echo "$MERGED_PRS" | jq -r ".[$i].created_at")
              MERGED=$(echo "$MERGED_PRS" | jq -r ".[$i].merged_at")
              
              CREATED_TS=$(date -d "$CREATED" +%s)
              MERGED_TS=$(date -d "$MERGED" +%s)
              
              DIFF_SECS=$(($MERGED_TS - $CREATED_TS))
              PR_HOURS=$(echo "scale=2; $DIFF_SECS / 3600" | bc)
              
              TOTAL_HOURS=$(echo "scale=2; $TOTAL_HOURS + $PR_HOURS" | bc)
            done
            
            # Calculate average
            AVG_HOURS=$(echo "scale=2; $TOTAL_HOURS / $PR_COUNT" | bc)
            
            # Format the output
            if (( $(echo "$AVG_HOURS < 24" | bc -l) )); then
              LT_VALUE="$AVG_HOURS hours"
              LT_LEVEL="Elite"
              LT_COLOR="brightgreen"
            elif (( $(echo "$AVG_HOURS < 168" | bc -l) )); then
              AVG_DAYS=$(echo "scale=2; $AVG_HOURS / 24" | bc)
              LT_VALUE="$AVG_DAYS days"
              LT_LEVEL="High"
              LT_COLOR="green"
            elif (( $(echo "$AVG_HOURS < 720" | bc -l) )); then
              AVG_DAYS=$(echo "scale=2; $AVG_HOURS / 24" | bc)
              LT_VALUE="$AVG_DAYS days"
              LT_LEVEL="Medium"
              LT_COLOR="yellow"
            else
              AVG_DAYS=$(echo "scale=2; $AVG_HOURS / 24" | bc)
              LT_VALUE="$AVG_DAYS days"
              LT_LEVEL="Low"
              LT_COLOR="red"
            fi
          else
            LT_VALUE="N/A (No PRs)"
            LT_LEVEL="N/A"
            LT_COLOR="gray"
          fi
          
          echo "lt_value=$LT_VALUE" >> $GITHUB_OUTPUT
          echo "lt_level=$LT_LEVEL" >> $GITHUB_OUTPUT
          echo "lt_color=$LT_COLOR" >> $GITHUB_OUTPUT
      
      # Create lead time badge data
      - name: Generate Lead Time Badge
        run: |
          cat > .github/badges/lead-time.json << EOF
          {
            "schemaVersion": 1,
            "label": "Lead Time",
            "message": "${{ steps.lead-time.outputs.lt_value }} (${{ steps.lead-time.outputs.lt_level }})",
            "color": "${{ steps.lead-time.outputs.lt_color }}"
          }
          EOF
      
      #############################################################
      # 3. Change Failure Rate
      #############################################################
      
      # Calculate Change Failure Rate
      - name: Calculate Change Failure Rate
        id: change-failure-rate
        run: |
          # Get date 30 days ago in ISO format
          THIRTY_DAYS_AGO=$(date -d "30 days ago" -u +"%Y-%m-%dT%H:%M:%SZ")
          
          # Count closed issues with bug or incident labels in last 30 days
          INCIDENT_COUNT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=closed&labels=bug,incident&since=$THIRTY_DAYS_AGO&per_page=100" \
            | jq '. | length')
          
          if [ -z "$INCIDENT_COUNT" ] || [ "$INCIDENT_COUNT" == "null" ]; then
            INCIDENT_COUNT=0
          fi
          
          # Check if we have any deployments
          if [ "${{ steps.deployment-frequency.outputs.deploy_count }}" -gt 0 ]; then
            RATE=$(echo "scale=2; $INCIDENT_COUNT / ${{ steps.deployment-frequency.outputs.deploy_count }} * 100" | bc)
            
            # Format the value
            if (( $(echo "$RATE <= 15" | bc -l) )); then
              CFR_LEVEL="Elite"
              CFR_COLOR="brightgreen"
            elif (( $(echo "$RATE <= 30" | bc -l) )); then
              CFR_LEVEL="High"
              CFR_COLOR="green"
            elif (( $(echo "$RATE <= 45" | bc -l) )); then
              CFR_LEVEL="Medium"
              CFR_COLOR="yellow"
            else
              CFR_LEVEL="Low"
              CFR_COLOR="red"
            fi
            
            FAILURE_RATE="${RATE}%"
          else
            FAILURE_RATE="N/A (No deployments)"
            CFR_LEVEL="N/A"
            CFR_COLOR="gray"
          fi
          
          echo "failure_rate=$FAILURE_RATE" >> $GITHUB_OUTPUT
          echo "cfr_level=$CFR_LEVEL" >> $GITHUB_OUTPUT
          echo "cfr_color=$CFR_COLOR" >> $GITHUB_OUTPUT
      
      # Create change failure rate badge data
      - name: Generate Change Failure Rate Badge
        run: |
          cat > .github/badges/change-failure-rate.json << EOF
          {
            "schemaVersion": 1,
            "label": "Change Failure Rate",
            "message": "${{ steps.change-failure-rate.outputs.failure_rate }} (${{ steps.change-failure-rate.outputs.cfr_level }})",
            "color": "${{ steps.change-failure-rate.outputs.cfr_color }}"
          }
          EOF
      
      #############################################################
      # 4. Mean Time to Recovery (MTTR)
      #############################################################
      
      # Calculate MTTR
      - name: Calculate MTTR from Issues
        id: mttr
        run: |
          # Get all issues labeled as incidents with closed timestamps
          ISSUES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues?state=closed&labels=incident&per_page=100")
          
          # Calculate time from opened to closed
          TOTAL_TIME=0
          COUNT=$(echo "$ISSUES" | jq '. | length')
          
          if [ "$COUNT" -gt 0 ]; then
            for i in $(seq 0 $(($COUNT-1))); do
              CREATED=$(echo "$ISSUES" | jq -r ".[$i].created_at")
              CLOSED=$(echo "$ISSUES" | jq -r ".[$i].closed_at")
              
              CREATED_TS=$(date -d "$CREATED" +%s)
              CLOSED_TS=$(date -d "$CLOSED" +%s)
              
              DIFF_SECS=$(($CLOSED_TS - $CREATED_TS))
              TOTAL_TIME=$(($TOTAL_TIME + $DIFF_SECS))
            done
            
            # Convert to hours
            AVG_HOURS=$(echo "scale=2; $TOTAL_TIME / $COUNT / 3600" | bc)
            
            # Format output
            if (( $(echo "$AVG_HOURS < 1" | bc -l) )); then
              MTTR_VALUE="${AVG_HOURS} hours"
              MTTR_LEVEL="Elite"
              MTTR_COLOR="brightgreen"
            elif (( $(echo "$AVG_HOURS < 24" | bc -l) )); then
              MTTR_VALUE="${AVG_HOURS} hours"
              MTTR_LEVEL="High"
              MTTR_COLOR="green"
            elif (( $(echo "$AVG_HOURS < 168" | bc -l) )); then
              MTTR_VALUE="${AVG_HOURS} hours"
              MTTR_LEVEL="Medium"
              MTTR_COLOR="yellow"
            else
              AVG_DAYS=$(echo "scale=2; $AVG_HOURS / 24" | bc)
              MTTR_VALUE="${AVG_DAYS} days"
              MTTR_LEVEL="Low"
              MTTR_COLOR="red"
            fi
          else
            MTTR_VALUE="N/A (No incidents)"
            MTTR_LEVEL="N/A"
            MTTR_COLOR="gray"
          fi
          
          echo "mttr_value=$MTTR_VALUE" >> $GITHUB_OUTPUT
          echo "mttr_level=$MTTR_LEVEL" >> $GITHUB_OUTPUT
          echo "mttr_color=$MTTR_COLOR" >> $GITHUB_OUTPUT
      
      # Create MTTR badge data
      - name: Generate MTTR Badge
        run: |
          cat > .github/badges/mttr.json << EOF
          {
            "schemaVersion": 1,
            "label": "MTTR",
            "message": "${{ steps.mttr.outputs.mttr_value }} (${{ steps.mttr.outputs.mttr_level }})",
            "color": "${{ steps.mttr.outputs.mttr_color }}"
          }
          EOF
      
      #############################################################
      # 5. Generate combined DORA badge
      #############################################################
      
      - name: Generate Combined DORA Badge
        run: |
          cat > .github/badges/dora-metrics.json << EOF
          {
            "schemaVersion": 1,
            "label": "DORA Metrics",
            "message": "DF: ${{ steps.deployment-frequency.outputs.df_level }} | LT: ${{ steps.lead-time.outputs.lt_level }} | CFR: ${{ steps.change-failure-rate.outputs.cfr_level }} | MTTR: ${{ steps.mttr.outputs.mttr_level }}",
            "color": "blue"
          }
          EOF
      
      #############################################################
      # 6. Create markdown report
      #############################################################
      
      - name: Create DORA Metrics Report
        run: |
          echo "# DORA Metrics Report" > dora-metrics.md
          echo "Generated on $(date)" >> dora-metrics.md
          echo "" >> dora-metrics.md
          echo "## Deployment Frequency" >> dora-metrics.md
          echo "**Value:** ${{ steps.deployment-frequency.outputs.df_value }}" >> dora-metrics.md
          echo "**Performance Level:** ${{ steps.deployment-frequency.outputs.df_level }}" >> dora-metrics.md
          echo "" >> dora-metrics.md
          echo "## Lead Time for Changes" >> dora-metrics.md
          echo "**Value:** ${{ steps.lead-time.outputs.lt_value }}" >> dora-metrics.md
          echo "**Performance Level:** ${{ steps.lead-time.outputs.lt_level }}" >> dora-metrics.md
          echo "" >> dora-metrics.md
          echo "## Change Failure Rate" >> dora-metrics.md
          echo "**Value:** ${{ steps.change-failure-rate.outputs.failure_rate }}" >> dora-metrics.md
          echo "**Performance Level:** ${{ steps.change-failure-rate.outputs.cfr_level }}" >> dora-metrics.md
          echo "" >> dora-metrics.md
          echo "## Mean Time to Recovery" >> dora-metrics.md
          echo "**Value:** ${{ steps.mttr.outputs.mttr_value }}" >> dora-metrics.md
          echo "**Performance Level:** ${{ steps.mttr.outputs.mttr_level }}" >> dora-metrics.md
          echo "" >> dora-metrics.md
          echo "## How to Add Badges to Your README" >> dora-metrics.md
          echo '```markdown' >> dora-metrics.md
          echo "<!-- DORA Metrics Badges -->" >> dora-metrics.md
          echo "![Deployment Frequency](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/${{ github.repository }}/main/.github/badges/deployment-frequency.json)" >> dora-metrics.md
          echo "![Lead Time for Changes](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/${{ github.repository }}/main/.github/badges/lead-time.json)" >> dora-metrics.md
          echo "![Change Failure Rate](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/${{ github.repository }}/main/.github/badges/change-failure-rate.json)" >> dora-metrics.md
          echo "![MTTR](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/${{ github.repository }}/main/.github/badges/mttr.json)" >> dora-metrics.md
          echo "![DORA Metrics](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/${{ github.repository }}/main/.github/badges/dora-metrics.json)" >> dora-metrics.md
          echo '```' >> dora-metrics.md
      
      #############################################################
      # 7. Save results
      #############################################################
      
      # Save metrics report as an artifact
      - name: Save DORA Metrics Report
        uses: actions/upload-artifact@v3
        with:
          name: dora-metrics-report
          path: dora-metrics.md
          
      # Commit badge data files
      - name: Commit badge data files
        uses: EndBug/add-and-commit@v9
        with:
          add: '.github/badges/*.json'
          message: 'Update DORA metrics badges [skip ci]'
          default_author: github_actions
      
      # Optionally create GitHub Issue with the report
      - name: Create GitHub Issue with Report
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const reportContent = fs.readFileSync('dora-metrics.md', 'utf8');
            
            // Check if there's an existing open issue with the same title pattern
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'dora-metrics'
            });
            
            const today = new Date().toISOString().split('T')[0];
            const issueTitle = `DORA Metrics Report - ${today}`;
            
            const existingIssue = issues.data.find(issue => 
              issue.title.startsWith('DORA Metrics Report -'));
            
            if (existingIssue) {
              // Update existing issue
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: existingIssue.number,
                title: issueTitle,
                body: reportContent
              });
              console.log(`Updated existing issue #${existingIssue.number}`);
            } else {
              // Create new issue
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issueTitle,
                body: reportContent,
                labels: ['metrics', 'dora-metrics']
              });
              console.log('Created new DORA metrics issue');
            }