name: Run Python Script
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.TOKEN }}  # or secrets.PAT if you named it PAT
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run script
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Make token available to script
      run: |
        python leaderboard.py examples/slim-fprime-config.json --output_format MARKDOWN --unsorted --emoji >> examples/slim-fprime-leaderboard.md
        python leaderboard.py examples/slim-ammos-config.json --output_format MARKDOWN --unsorted --emoji >> examples/slim-ammos-leaderboard.md
